# Adds namespace to all resources.
namespace: default

# Value of this field is prepended to the
# names of all resources, e.g. a deployment named
# "wordpress" becomes "alices-wordpress".
# Note that it should also match with the prefix (text before '-') of the namespace
# field above.
namePrefix: bmo-

# Labels to add to all resources and selectors.
#commonLabels:
#  someName: someValue

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml
# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'. 'WEBHOOK' components are required.
resources:
- crds
- rbac
- manager.yaml
- webhook
- certmanager
# [PROMETHEUS] To enable prometheus monitor, uncomment all sections with 'PROMETHEUS'.
#- prometheus

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config

# Protect the /metrics endpoint by putting it behind auth.
# If you want your controller-manager to expose the /metrics
# endpoint w/o any authn/z, please comment the following line.

# Mount the controller config file for loading manager configurations
# through a ComponentConfig type
#- manager_config_patch.yaml

# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix including the one in
# crd/kustomization.yaml

# [CERTMANAGER] To enable cert-manager, uncomment all sections with 'CERTMANAGER'.
# Uncomment 'CERTMANAGER' sections in crd/kustomization.yaml to enable the CA injection in the admission webhooks.
# 'CERTMANAGER' needs to be enabled to use ca injection
patches:
- path: manager_auth_proxy_patch.yaml
- path: manager_webhook_patch.yaml
- path: webhookcainjection_patch.yaml

replacements:
- source:
    fieldPath: metadata.namespace
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
    select:
      kind: ValidatingWebhookConfiguration
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
    select:
      kind: CustomResourceDefinition
      name: baremetalhosts.metal3.io
- source:
    fieldPath: metadata.name
    group: cert-manager.io
    kind: Certificate
    name: serving-cert
    version: v1
  targets:
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      kind: ValidatingWebhookConfiguration
  - fieldPaths:
    - metadata.annotations.[cert-manager.io/inject-ca-from]
    options:
      delimiter: /
      index: 1
    select:
      kind: CustomResourceDefinition
      name: baremetalhosts.metal3.io
- source:
    fieldPath: metadata.namespace
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
      index: 1
    select:
      kind: Certificate
- source:
    fieldPath: metadata.name
    kind: Service
    name: webhook-service
    version: v1
  targets:
  - fieldPaths:
    - spec.dnsNames.*
    options:
      delimiter: .
    select:
      kind: Certificate
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/metal3-io/baremetal-operator
  newName: registry.paas/cmetal/baremetal-operator
  newTag: v0.6.1
