apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cmetal
namePrefix: baremetal-operator-
resources:
  - ../base
configMapGenerator:
  - envs:
      - ironic_bmo_configmap.env
    name: ironic-bmo-configmap
