apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cmetal
resources:
  - https://github.com/metal3-io/baremetal-operator/config/namespace?ref=release-0.5&timeout=120s
  - https://github.com/metal3-io/baremetal-operator/ironic-deployment/base?ref=release-0.5&timeout=120s

components:
  - https://github.com/metal3-io/baremetal-operator/ironic-deployment/components/basic-auth?ref=release-0.5&timeout=120s
  - https://github.com/metal3-io/baremetal-operator/ironic-deployment/components/tls?ref=release-0.5&timeout=120s

configMapGenerator:
  - envs:
      - ironic_bmo_configmap.env
    name: ironic-bmo-configmap
    behavior: create

patches:
  - path: ironic-patch.yaml

images:
  - name: quay.io/metal3-io/ironic
    newTag: release-24.0

# NOTE: These credentials are generated automatically in hack/ci-e2e.sh
secretGenerator:
  - name: ironic-htpasswd
    behavior: create
    files:
      - htpasswd=ironic-htpasswd
  - name: ironic-inspector-htpasswd
    behavior: create
    files:
      - htpasswd=ironic-inspector-htpasswd
  - name: ironic-auth-config
    files:
      - auth-config=ironic-auth-config
  - name: ironic-inspector-auth-config
    files:
      - auth-config=ironic-inspector-auth-config

replacements:
  # Replace IRONIC_HOST_IP in certificates with the PROVISIONING_IP from the configmap
  - source:
      kind: ConfigMap
      name: ironic-bmo-configmap
      fieldPath: .data.PROVISIONING_IP
    targets:
      - select:
          version: v1
          group: cert-manager.io
          kind: Certificate
          name:
        fieldPaths:
          - .spec.ipAddresses.0
